before_script:
  - py --version
  - py -m pip --version

stages:
  - lint
  - type_check
  - test
  - coverage
  - security

lint:
  stage: lint
  script:
    - py -m pip install ruff
    - py -m ruff check .

type_check:
  stage: type_check
  script:
    - py -m pip install mypy
    - py -m mypy .

test:
  stage: test
  script:
    - py -m pip install pytest
    - py -m pytest

coverage:
  stage: coverage
  script:
    - py -m pip install pytest pytest-cov
    - py -m pytest --cov=. --cov-report=xml

security:
  stage: security
  script:
    - py -m pip install pip-audit bandit
    - py -m pip_audit
    - py -m bandit -r .