before_script:
  - '& "C:\Users\MANASVI_P\AppData\Local\Programs\Python\Python314\python.exe" --version'
  - '& "C:\Users\MANASVI_P\AppData\Local\Programs\Python\Python314\python.exe" -m pip --version'

stages:
  - lint
  - type_check
  - test
  - coverage
  - security

lint:
  stage: lint
  script:
    - '& "C:\Users\MANASVI_P\AppData\Local\Programs\Python\Python314\python.exe" -m pip install ruff'
    - '& "C:\Users\MANASVI_P\AppData\Local\Programs\Python\Python314\python.exe" -m ruff check .'

type_check:
  stage: type_check
  script:
    - '& "C:\Users\MANASVI_P\AppData\Local\Programs\Python\Python314\python.exe" -m pip install mypy'
    - '& "C:\Users\MANASVI_P\AppData\Local\Programs\Python\Python314\python.exe" -m mypy --explicit-package-bases .'

test:
  stage: test
  script:
    - '& "C:\Users\MANASVI_P\AppData\Local\Programs\Python\Python314\python.exe" -m pip install pytest'
    - '& "C:\Users\MANASVI_P\AppData\Local\Programs\Python\Python314\python.exe" -m pytest'

coverage:
  stage: coverage
  script:
    - '& "C:\Users\MANASVI_P\AppData\Local\Programs\Python\Python314\python.exe" -m pip install pytest pytest-cov'
    - '& "C:\Users\MANASVI_P\AppData\Local\Programs\Python\Python314\python.exe" -m pytest --cov=. --cov-report=xml'

security:
  stage: security
  script:
    - '& "C:\Users\MANASVI_P\AppData\Local\Programs\Python\Python314\python.exe" -m pip install pip-audit bandit'
    - '& "C:\Users\MANASVI_P\AppData\Local\Programs\Python\Python314\python.exe" -m pip_audit'
    - '& "C:\Users\MANASVI_P\AppData\Local\Programs\Python\Python314\python.exe" -m bandit -r .'